apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dutch-zebra-dotnet-basic 
  janus-idp.io/tekton: dutch-zebra-dotnet-basic
  backstage.io/kubernetes-id: dutch-zebra-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: dutch-zebra-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  